version: '3.8'

x-network: &NETWORK
  # for Virtual machine
  network_mode: host
  # for Container
  # networks:
  #   internal:

networks:
  internal:
    name: internal
    external: true

services:
  tailscale:
    image: tailscale/tailscale
    container_name: tailscale
    hostname: tailscale
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined
    <<: [*NETWORK]
    volumes:
      - /var/lib:/var/lib
      - /dev/net/tun:/dev/net/tun
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    restart: always
    command: tailscaled
